export const ActionTypes = {
    CHANGE_EDIT_STATE_SUPPLIER_KEY:"CHANGE_EDIT_STATE_SUPPLIER_KEY",
    CHANGE_EDIT_STATE_SUPPLIER_PRODUCT:"CHANGE_EDIT_STATE_SUPPLIER_PRODUCT",
    CHANGE_EDIT_STATE_SUPPLIER_SIGNATURE:"CHANGE_EDIT_STATE_SUPPLIER_SIGNATURE",
    CHANGE_EDIT_STATE_TRANSPORT_KEY:"CHANGE_EDIT_STATE_TRANSPORT_KEY",
    CHANGE_EDIT_STATE_TRANSPORT_PRODUCT:"CHANGE_EDIT_STATE_TRANSPORT_PRODUCT",
    CHANGE_EDIT_STATE_ACCREDITATION_KEY:"CHANGE_EDIT_STATE_ACCREDITATION_KEY",
    CHANGE_CHANGE_STATE_TABLECHAINBLOCK:"CHANGE_CHANGE_STATE_TABLECHAINBLOCK",
    CHANGE_CHANGE_STATE_SIDERBAR_SUPPLIER:"CHANGE_CHANGE_STATE_SIDERBAR_SUPPLIER",
    CHANGE_CHANGE_STATE_SIDERBAR_TRANSPORT:"CHANGE_CHANGE_STATE_SIDERBAR_TRANSPOR",
    CHANGE_CHANGE_STATE_SIDERBAR_ACCREDITATION:"CHANGE_CHANGE_STATE_SIDERBAR_ACCREDITATION",
    GET_KEY_SUPPLIER:"GET_KEY_SUPPLIER",
    GET_DATA_SUPPLIER:"GET_DATA_SUPPLIER",
    REMOVE_DATA_SUPPLIER_COMFIRM:"REMOVE_DATA_SUPPLIER_COMFIRM",
    CHANGE_CHANGE_STATE_BUTTON_CONFIRM:"CHANGE_CHANGE_STATE_BUTTON_CONFIRM",
    GET_DATA_TRANSPORT:"GET_DATA_TRANSPORT",
    GET_CHAIN_BLOCK:"GET_CHAIN_BLOCK",
    DELETE_DATA_TRANSPORT : "DELETE_DATA_TRANSPORT"
}